[[data]]
order = 2
group = 0
query = [
    "--alpha=one",
    "--beta",
    "two",
    "-a",
    "-bthree",
    "final",
]
solution = [
    "--alpha=one",
    "--beta",
    "two",
    "-a",
    "-bthree",
    "final",
]

[data.optdict]
--alpha = 1
--beta = 1
-a = 0
-b = 1

[[data]]
order = 2
group = 0
query = [
    "-abcval",
    "--set",
    "x",
    "y",
    "arg1",
]
solution = [
    "-a",
    "-b",
    "-cval",
    "--set",
    "x",
    "y",
    "arg1",
]

[data.optdict]
-a = 0
-b = 0
-c = 1
--set = 2

[[data]]
order = 2
group = 0
query = [
    "input.txt",
    "--log=logfile",
    "-acextra",
    "--debug",
    "file.csv",
]
solution = [
    "--log=logfile",
    "-a",
    "-cextra",
    "--debug",
    "input.txt",
    "file.csv",
]

[data.optdict]
-a = 0
-b = 1
-c = 2
--log = 1
--debug = 0
--config = 2

[[data]]
order = 1
group = 0
query = [
    "--debug",
    "-acextra",
    "--log=logfile",
    "input.txt",
    "--config",
    "settings",
]
solution = [
    "--debug",
    "-a",
    "-cextra",
    "--log=logfile",
    "input.txt",
    "--config",
    "settings",
]

[data.optdict]
-a = 0
-b = 1
-c = 2
--log = 1
--debug = 0
--config = 2

[[data]]
order = 0
group = 0
query = [
    "-xyval",
    "--mode=fast",
    "--file",
    "out.txt",
    "input.dat",
]
solution = [
    "-xyval",
    "--mode=fast",
    "--file",
    "out.txt",
    "input.dat",
]

[data.optdict]
-x = 2
-y = 1
--mode = 2
--file = 1
